### ISSUE TITLE
Error After Creating Q&A

### ISSUE THREAD

**Issue by Felli** [ConnectedCommunities/humhub-modules-questionanswer#30]
The following error happens after you submit a question. :smile:
`"name":"Internal Server Error","message":"There was an error at the server.","code":0,"status":500}`
After this clicking the question brings up the normal Internal Server Error message that is generated by Humhub. :frowning:

**Comment by benmag** [comment]
Hi @Felli 

Which branch are you using? We're currently upgrading this module (see the `upgrade` branch). 

If you're already using the `upgrade` branch let me know and I'll look into it further :+1:

**Comment by Felli** [comment]
The upgrade branch is the one I tested. :smile:

**Comment by benmag** [comment]
Hmm ok 

I can't replicate that, could you give me some more info about how I can replicate this and the output from your server log?

**Comment by Felli** [comment]
Well after uploading the module into the modules directory and enabling it, I went to the q&a page and typed in the question gave it a tag which after I submitted it it gave me that error. Could it be because of PrettyUrl being enabled?

**Comment by Felli** [comment]
Are there any dependencies while using this module?

**Comment by byronmejia** [comment]
Try using this module with it:
- [Karma](https://github.com/benmag/humhub-modules-karma)

**Comment by Felli** [comment]
@byronmejia still not working, same error when creating, and viewing questions. :frowning:

**Comment by byronmejia** [comment]
Using the upgrade branch for both modules?
`git checkout upgrade`

**Comment by byronmejia** [comment]
Actually, just did a test from scratch. My modules look like this:
- QuestionAnswer (upgrade branch)

And no Karma module.

**Comment by benmag** [comment]
I haven't tested it with prettyUrl's enabled, so it might have something to do with that

**Comment by Felli** [comment]
Disabling PrettyUrl's doesn't help sadly. :frowning:

**Comment by benmag** [comment]
Strange...

What web server are you using? I'd really need to see a copy of your server logs to hopefully get a better idea of what's going on

**Comment by Felli** [comment]
I'm using x10Premium which their servers are Linux if I believe. Also for the logs I'm working on this now.

**Comment by Felli** [comment]
@benmag would it be possible to email you the logs?

**Comment by benmag** [comment]
sure: ben.maggacis(at)qut.edu.au

(I'll delete this comment after you've sent it ;) )

**Comment by benmag** [comment]
Apache or NGINX?

**Comment by Felli** [comment]
Apache

**Comment by benmag** [comment]
This is strange. I'm using Apache 2.0 as well and not having any troubles so I'm not sure what it could be

**Comment by Felli** [comment]
Could it be because of me using PHP 5.5?

**Comment by petersmithca** [comment]
I actually got the exact same error on a pretty much brand new install.  heres the apache error.  Looking for a module named karma?  PHP Fatal error:  Class 'humhub\modules\karma\models\Karma' not found in /var/www/showcase/protected/modules/questionanswer/Eve

**Comment by petersmithca** [comment]
I've not tried the karma module yet tho. I wonder if the module.json supports a "require" parameter to allow you to specify that the module requires the other somehow.

**Comment by benmag** [comment]
Hmm ok. That is a lot clearer now! Thanks @petersmithca 

Seems I accidentally wrote some code that assumed the Karma module was available to this questionanswer module.

This should be fixed when I merge the `spaces` branch into master.

**Comment by theankush** [comment]
An internal server error occurred on submitting the question
Here is the screenshot:- https://prnt.sc/m65y7j

And the server log is
`Sat, 12 Jan 2019 13:42:38 +0530  application $_GET = [ 'r' => 'questionanswer/question/create' '_pjax' => '#layout-content' '_' => '1547280652072' ] $_SERVER = [ 'CONTENT_LENGTH' => '463' 'CONTENT_TYPE' => 'application/x-www-form-urlencoded' 'CONTEXT_DOCUMENT_ROOT' => '/home/frantzrx/frantiger.club' 'CONTEXT_PREFIX' => '' 'DOCUMENT_ROOT' => '/home/frantzrx/frantiger.club' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'H2PUSH' => 'on' 'H2_PUSH' => 'on' 'H2_PUSHED' => '' 'H2_PUSHED_ON' => '' 'H2_STREAM_ID' => '3' 'H2_STREAM_TAG' => '259-3' 'HTTP2' => 'on' 'HTTPS' => 'on' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_ACCEPT_LANGUAGE' => 'en,en-US;q=0.9,hi;q=0.8' 'HTTP_CACHE_CONTROL' => 'max-age=0' 'HTTP_COOKIE' => '_ga=GA1.2.205806930.1545284215; pm_panel-activities=expanded; _gid=GA1.2.1188144075.1547048740; pm_space-members-panel=expanded; pm_user-spaces-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_user-tags-panel=expanded; language=555aeec7f6c25eb79857c3a1981a4d99ac96524b862dbc6946cd86c124e8ad50a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; pm_profile-friends-panel=expanded; pm_groups-statistics-panel=expanded; pm_spaces-statistics-panel=expanded; pm_panel-pinterest=expanded; PHPSESSID=5dd77e48749263b59bcb6cdb67048c34; _identity=e1293e16097f5bdcc8422858a23260a00eef9d0c70eb253df890278cef7d8a76a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22ba209146-17c2-44e7-8c4c-b1259338647c%22%2C2592000%5D%22%3B%7D; _csrf=9cb98305115e03f6b164036bd95f9f19d841929c0f2be6d470e0592d797ee9e3a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22AbxEIr25TnxUpeeRFXbuoHH4-WPET1Ya%22%3B%7D; pm_getting-started-panel=collapsed; pm_calendar-upcoming-events-snippet=expanded' 'HTTP_DNT' => '1' 'HTTP_HOST' => 'frantiger.club' 'HTTP_ORIGIN' => 'https://frantiger.club' 'HTTP_REFERER' => 'https://frantiger.club/index.php?r=questionanswer%2Fquestion%2Fcreate' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' 'HTTP_X_HTTPS' => '1' 'PATH' => '/bin:/usr/bin' 'QUERY_STRING' => 'r=questionanswer%2Fquestion%2Fcreate&_pjax=%23layout-content&_=1547280652072' 'REDIRECT_STATUS' => '200' 'REMOTE_ADDR' => '157.49.141.119' 'REMOTE_PORT' => '22212' 'REQUEST_METHOD' => 'POST' 'REQUEST_SCHEME' => 'https' 'REQUEST_URI' => '/index.php?r=questionanswer%2Fquestion%2Fcreate&_pjax=%23layout-content&_=1547280652072' 'SCRIPT_FILENAME' => '/home/frantzrx/frantiger.club/index.php' 'SCRIPT_NAME' => '/index.php' 'SCRIPT_URI' => 'https://frantiger.club/index.php' 'SCRIPT_URL' => '/index.php' 'SERVER_ADDR' => '172.104.63.228' 'SERVER_ADMIN' => 'webmaster@club.frantiger.com' 'SERVER_NAME' => 'frantiger.club' 'SERVER_PORT' => '443' 'SERVER_PROTOCOL' => 'HTTP/2.0' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SSL_TLS_SNI' => 'frantiger.club' 'UNIQUE_ID' => 'XDmhdl75hWg4t9Wtwyo7DAAAAAM' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1547280758.9354 'REQUEST_TIME' => 1547280758 'argv' => [ 0 => 'r=questionanswer%2Fquestion%2Fcreate&_pjax=%23layout-content&_=1547280652072' ] 'argc' => 1 ]
ERROR  Sat, 12 Jan 2019 13:42:39 +0530  yii\base\UnknownPropertyException yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\questionanswer\models\Question::pinned in /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/Component.php:154 Stack trace: #0 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\base\Component->__get('pinned') #1 /home/frantzrx/frantiger.club/protected/humhub/modules/content/components/ContentActiveRecord.php(192): yii\db\BaseActiveRecord->__get('pinned') #2 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/validators/Validator.php(264): humhub\modules\content\components\ContentActiveRecord->__get('pinned') #3 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(humhub\modules\questionanswer\models\Question), Array) #4 /home/frantzrx/frantiger.club/protected/modules/humhub-modules-questionanswer-master/controllers/QuestionController.php(182): yii\base\Model->validate() #5 [internal function]: humhub\modules\questionanswer\controllers\QuestionController->actionCreate() #6 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #7 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #8 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('create', Array) #9 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('questionanswer/...', Array) #10 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #11 /home/frantzrx/frantiger.club/index.php(25): yii\base\Application->run() #12 {main}
INFO  Sat, 12 Jan 2019 13:21:12 +0530  application $_GET = [ 'r' => 'questionanswer/comment/admin' ] $_SERVER = [ 'CONTEXT_DOCUMENT_ROOT' => '/home/frantzrx/frantiger.club' 'CONTEXT_PREFIX' => '' 'DOCUMENT_ROOT' => '/home/frantzrx/frantiger.club' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'H2PUSH' => 'on' 'H2_PUSH' => 'on' 'H2_PUSHED' => '' 'H2_PUSHED_ON' => '' 'H2_STREAM_ID' => '9' 'H2_STREAM_TAG' => '215-9' 'HTTP2' => 'on' 'HTTPS' => 'on' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_ACCEPT_LANGUAGE' => 'en,en-US;q=0.9,hi;q=0.8' 'HTTP_COOKIE' => '_ga=GA1.2.205806930.1545284215; pm_panel-activities=expanded; _gid=GA1.2.1188144075.1547048740; pm_space-members-panel=expanded; pm_user-spaces-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_user-tags-panel=expanded; language=555aeec7f6c25eb79857c3a1981a4d99ac96524b862dbc6946cd86c124e8ad50a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; pm_profile-friends-panel=expanded; pm_groups-statistics-panel=expanded; pm_spaces-statistics-panel=expanded; pm_panel-pinterest=expanded; pm_getting-started-panel=expanded; PHPSESSID=5dd77e48749263b59bcb6cdb67048c34; _identity=e1293e16097f5bdcc8422858a23260a00eef9d0c70eb253df890278cef7d8a76a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22ba209146-17c2-44e7-8c4c-b1259338647c%22%2C2592000%5D%22%3B%7D; _csrf=9cb98305115e03f6b164036bd95f9f19d841929c0f2be6d470e0592d797ee9e3a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22AbxEIr25TnxUpeeRFXbuoHH4-WPET1Ya%22%3B%7D' 'HTTP_DNT' => '1' 'HTTP_HOST' => 'frantiger.club' 'HTTP_REFERER' => 'https://frantiger.club/index.php?r=questionanswer%2Fanswer%2Fadmin' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' 'HTTP_X_HTTPS' => '1' 'PATH' => '/bin:/usr/bin' 'QUERY_STRING' => 'r=questionanswer%2Fcomment%2Fadmin' 'REDIRECT_STATUS' => '200' 'REMOTE_ADDR' => '157.49.141.119' 'REMOTE_PORT' => '17976' 'REQUEST_METHOD' => 'GET' 'REQUEST_SCHEME' => 'https' 'REQUEST_URI' => '/index.php?r=questionanswer%2Fcomment%2Fadmin' 'SCRIPT_FILENAME' => '/home/frantzrx/frantiger.club/index.php' 'SCRIPT_NAME' => '/index.php' 'SCRIPT_URI' => 'https://frantiger.club/index.php' 'SCRIPT_URL' => '/index.php' 'SERVER_ADDR' => '172.104.63.228' 'SERVER_ADMIN' => 'webmaster@club.frantiger.com' 'SERVER_NAME' => 'frantiger.club' 'SERVER_PORT' => '443' 'SERVER_PROTOCOL' => 'HTTP/2.0' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SSL_TLS_SNI' => 'frantiger.club' 'UNIQUE_ID' => 'XDmccEfMSYTVR8FY6sfwZgAAAAk' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1547279472.6427 'REQUEST_TIME' => 1547279472 'argv' => [ 0 => 'r=questionanswer%2Fcomment%2Fadmin' ] 'argc' => 1 ]
ERROR  Sat, 12 Jan 2019 13:21:12 +0530  yii\base\ErrorException:2 yii\base\ErrorException: Declaration of humhub\modules\questionanswer\models\CommentSearch::search($params) should be compatible with humhub\modules\questionanswer\models\Comment::search() in /home/frantzrx/frantiger.club/protected/modules/humhub-modules-questionanswer-2.0/models/CommentSearch.php:30 Stack trace: #0 /home/frantzrx/frantiger.club/protected/modules/humhub-modules-questionanswer-2.0/models/CommentSearch.php(30): yii\base\ErrorHandler->handleError(2, 'Declaration of ...', '/home/frantzrx/...', 30, Array) #1 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/BaseYii.php(293): include('/home/frantzrx/...') #2 [internal function]: yii\BaseYii::autoload('humhub\\modules\\...') #3 /home/frantzrx/frantiger.club/protected/modules/humhub-modules-questionanswer-2.0/controllers/CommentController.php(131): spl_autoload_call('humhub\\modules\\...') #4 [internal function]: humhub\modules\questionanswer\controllers\CommentController->actionAdmin() #5 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #6 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #7 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('admin', Array) #8 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('questionanswer/...', Array) #9 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /home/frantzrx/frantiger.club/index.php(25): yii\base\Application->run() #11 {main}
INFO  Sat, 12 Jan 2019 13:21:12 +0530  application $_GET = [ 'r' => 'questionanswer/comment/admin' '_pjax' => '#layout-content' '_' => '1547279327981' ] $_SERVER = [ 'CONTENT_LENGTH' => '0' 'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8' 'CONTEXT_DOCUMENT_ROOT' => '/home/frantzrx/frantiger.club' 'CONTEXT_PREFIX' => '' 'DOCUMENT_ROOT' => '/home/frantzrx/frantiger.club' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'H2PUSH' => 'on' 'H2_PUSH' => 'on' 'H2_PUSHED' => '' 'H2_PUSHED_ON' => '' 'H2_STREAM_ID' => '7' 'H2_STREAM_TAG' => '215-7' 'HTTP2' => 'on' 'HTTPS' => 'on' 'HTTP_ACCEPT' => 'text/html, */*; q=0.01' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_ACCEPT_LANGUAGE' => 'en,en-US;q=0.9,hi;q=0.8' 'HTTP_COOKIE' => '_ga=GA1.2.205806930.1545284215; pm_panel-activities=expanded; _gid=GA1.2.1188144075.1547048740; pm_space-members-panel=expanded; pm_user-spaces-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_user-tags-panel=expanded; language=555aeec7f6c25eb79857c3a1981a4d99ac96524b862dbc6946cd86c124e8ad50a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; pm_profile-friends-panel=expanded; pm_groups-statistics-panel=expanded; pm_spaces-statistics-panel=expanded; pm_panel-pinterest=expanded; pm_getting-started-panel=expanded; PHPSESSID=5dd77e48749263b59bcb6cdb67048c34; _identity=e1293e16097f5bdcc8422858a23260a00eef9d0c70eb253df890278cef7d8a76a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22ba209146-17c2-44e7-8c4c-b1259338647c%22%2C2592000%5D%22%3B%7D; _csrf=9cb98305115e03f6b164036bd95f9f19d841929c0f2be6d470e0592d797ee9e3a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22AbxEIr25TnxUpeeRFXbuoHH4-WPET1Ya%22%3B%7D' 'HTTP_DNT' => '1' 'HTTP_HOST' => 'frantiger.club' 'HTTP_REFERER' => 'https://frantiger.club/index.php?r=questionanswer%2Fanswer%2Fadmin' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' 'HTTP_X_CSRF_TOKEN' => 'xVUgNtqt53xXv50JQODmK0bK8G0dbwRR0K72dIbrXFGEN1hzk9_VSQPR5VwwhYN5AJKSGHInTGX9-aYx0toFMA==' 'HTTP_X_HTTPS' => '1' 'HTTP_X_PJAX' => 'true' 'HTTP_X_PJAX_CONTAINER' => '#layout-content' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'PATH' => '/bin:/usr/bin' 'QUERY_STRING' => 'r=questionanswer%2Fcomment%2Fadmin&_pjax=%23layout-content&_=1547279327981' 'REDIRECT_STATUS' => '200' 'REMOTE_ADDR' => '157.49.141.119' 'REMOTE_PORT' => '17976' 'REQUEST_METHOD' => 'GET' 'REQUEST_SCHEME' => 'https' 'REQUEST_URI' => '/index.php?r=questionanswer%2Fcomment%2Fadmin&_pjax=%23layout-content&_=1547279327981' 'SCRIPT_FILENAME' => '/home/frantzrx/frantiger.club/index.php' 'SCRIPT_NAME' => '/index.php' 'SCRIPT_URI' => 'https://frantiger.club/index.php' 'SCRIPT_URL' => '/index.php' 'SERVER_ADDR' => '172.104.63.228' 'SERVER_ADMIN' => 'webmaster@club.frantiger.com' 'SERVER_NAME' => 'frantiger.club' 'SERVER_PORT' => '443' 'SERVER_PROTOCOL' => 'HTTP/2.0' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SSL_TLS_SNI' => 'frantiger.club' 'UNIQUE_ID' => 'XDmccEfMSYTVR8FY6sfwZQAAAAc' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1547279472.2673 'REQUEST_TIME' => 1547279472 'argv' => [ 0 => 'r=questionanswer%2Fcomment%2Fadmin&_pjax=%23layout-content&_=1547279327981' ] 'argc' => 1 ]
ERROR  Sat, 12 Jan 2019 13:21:12 +0530  yii\base\ErrorException:2 yii\base\ErrorException: Declaration of humhub\modules\questionanswer\models\CommentSearch::search($params) should be compatible with humhub\modules\questionanswer\models\Comment::search() in /home/frantzrx/frantiger.club/protected/modules/humhub-modules-questionanswer-2.0/models/CommentSearch.php:30 Stack trace: #0 /home/frantzrx/frantiger.club/protected/modules/humhub-modules-questionanswer-2.0/models/CommentSearch.php(30): yii\base\ErrorHandler->handleError(2, 'Declaration of ...', '/home/frantzrx/...', 30, Array) #1 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/BaseYii.php(293): include('/home/frantzrx/...') #2 [internal function]: yii\BaseYii::autoload('humhub\\modules\\...') #3 /home/frantzrx/frantiger.club/protected/modules/humhub-modules-questionanswer-2.0/controllers/CommentController.php(131): spl_autoload_call('humhub\\modules\\...') #4 [internal function]: humhub\modules\questionanswer\controllers\CommentController->actionAdmin() #5 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #6 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #7 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('admin', Array) #8 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('questionanswer/...', Array) #9 /home/frantzrx/frantiger.club/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /home/frantzrx/frantiger.club/index.php(25): yii\base\Application->run() #11 {main}`
