### ISSUE TITLE
Question and Feature Request

### ISSUE THREAD

**Issue by hfortune** [ConnectedCommunities/humhub-modules-questionanswer#34]
Hi - this is a great module - thank you!

I installed this with the global setting first, but then quickly decided I'd rather have each space have its own separate question and answer area, so I switched it to the space setting. However, I now still have a Q&A index on the top bar, but nothing seems to show up on that page. Is this the way it is supposed to be? Or should that be removed once I switch to the spaces setting versus the global setting? Or will questions show up on that page somehow? (The question that was showing up from one of our spaces is now not showing up, but there is no way to add questions or anything there either -- just a blank page). Can you let me know if that Q&A index is supposed to still be there and if so, what will show up on it? <grin> -- thanks!

As for the feature request, is it possible to have the questions show up in the stream as posts? I volunteer for a nonprofit support group and I really think this Q&A feature will be very well used by our membership, but I'm afraid it will get lost if the questions don't show up on the stream. How difficult would it be to add that?

Thank you again for this great module! I am already getting a lot of positive feedback having this option on our community!

Heather

**Comment by hfortune** [comment]
A couple additional questions (figured I'd just toss it in here!)
I was reading through the code and noticed that in the Q&A module, you already have some built in karma calls, so I added those names to the admin panel in Karma to see if I could get it to work.

I was pleasantly surprised that I could, and when I upvoted the question, I noted I got karma. I thought, wait -- shouldn't the person who posted the question get the karma? And I checked and she also had karma. And then I thought -- wait, only one person should be getting karma based on the code, so I checked and sure enough every single member of our community received a point of karma for my upvoting the question :)

Is there a way to fix that so that only the person upvoting receives the karma points?

I think I saw a closed issue on this, but wanted to point out I just experienced this: when I upvoted the comment, I was redirected to the Q&A index page (the one that is all blank). It did upvote the question, but put me on that page, so I had to go back to get back to the spaces q&A page and see my upvote. Is this fixable so that the voter isnt navigated away from the page when they upvote a question or answer?

Thank you!

**Comment by benmag** [comment]
Hi Heather

Thanks for the feedback :) 

This isn't documented at all so I'll need to fix that... But when you use the `Spaces` mode, that page becomes the Q&A index page, showing a categorised list of available Q&A forums. I haven't yet implemented something to handle Spaces that don't opt into the categorizations. 

For now, you can categorise them by using the giving the Space name the following format:

```
The Category > Topic
```

As for the feature request:
I've already implemented that but never added a way to enable/disable it from the admin panel. By default it's off but you can manually enable it by editing `questionanswer/models/Question.php` and changing `$autoAddToWall` to `true`.

I'll add it as an option to the admin panel this week.

As for the karma issue, that is a bug. Can you make a new issue for it, so I can keep track of it separately. 

Same with the upvote redirect. Not a bug per se but an experience that can and should be improved. A new issue for that will help me keep track of it too.

Ben

**Comment by hfortune** [comment]
Hi Ben! Thank you so much for your help! I will set up new issues for the other things in just a moment.

With regard to the Q&A issue, perhaps if I tell you what I am hoping to attain, you can help me ensure I have the best selection? We have a lot of spaces based on location and I would like them to have their own private q&a. We also have several public spaces that anyone can join and I'd like to have Q&A there that everyone can see. 

I do not want the people in one location space to see the questions/answers from another location space, but I do ideally want one central place where users can see ALL questions that they are allowed to see.

So I guess the question is, are the questions/answers permission based on spaces? If someone posts a question in a space, does it show up for everyone, even if they are not members of that space? If the index only shows the questions I'm allowed to see and respects space permissions, then it might actually be that I do want the global option instead.

PS - are you the same person who wrote the karma module? I have a couple questions on that too but haven't posted over there yet because I don't want to drive you crazy!

**Comment by benmag** [comment]
> We have a lot of spaces based on location and I would like them to have their own private q&a. We also have several public spaces that anyone can join and I'd like to have Q&A there that everyone can see.

The best way to do this is to use the module in Spaces mode. Enable the Q&A module for each of your spaces (the public and private ones).

Then go to the Q&A Admin settings and add each of the private spaces to the Hidden Category List.

That's the best option at this stage since there's no questions/answers permissions based on spaces yet (any PR's implementing this would are welcomed)
