### ISSUE TITLE
karma error static method ? and other...

### ISSUE THREAD

**Issue by LokyStaz** [ConnectedCommunities/humhub-modules-questionanswer#37]
Hi.. I get an error when voting on a question for example!!

> Non-static method humhub\modules\karma\models\Karma::addKarma() should not be called statically.

apparently coming from the event.php line 153...
`if(isset(Yii::  $app->modules['karma'])) {
 Karma::addKarma('question_up_vote', $event->sender->created_by);
}`

after a refresh, the question have the vote, but no karma add...
- And when I go to /questionanswer/question/index, the page is empty, no error juste empty (only the topbar show up) (but a /questionanswer/question/view?id=1 work)
- And it would be nice if the karma will be useful... (gain something after % of good karma... (such as a different badges (for start^^)to show on profile and directory and search)...
- And that would be nice to split Q/A in search results... Like the others, "all, content, users, space"....

Thanks for any help !!

**Comment by benmag** [comment]
Hi 

I assume you have the Karma module already installed.

Re Karma calling non-static, I believe that should be [fixed](https://github.com/ConnectedCommunities/humhub-modules-karma/commit/ba2eefe4147c0e1785c21f750d16eb94287cd6c0) if you update. If it's still happening, can you tell me where you're voting from (are you viewing the question or on the index?)

Re /questionanswer/question/index being empty
If you are using "Spaces" mode then that was expected if your space names wasn't formatted  `Category > Name`. I've just pushed an update to fix that so it will list the spaces with Q&A installed. 

Those suggestions (badges and Q/A split in search etc) are great ideas and definitely something we'd like to work towards implementing eventually.

**Comment by LokyStaz** [comment]
Thanks your fix worked!!
For the karma, the "patch" fix the error but karma is still not add ?!

For my suggestions, I think there is more important stuff before that... Such as "Categories" for the global Q/A...
I will try to explain me ^^ : for example if I create a "space" about bike mechanic (to help members with meca issues), what would be the point to have a Q/A inside that space, while most of the people (I'm sure of it (for my target members at least)) will just ask question in the space as a post and answer with comments)... So will be better to not create that space, but to create directly a "category" in the global Q/A.... What do you think?
(**edit:** Or a better integration in the space... Like : The number of question in the space header (such as posts, members...), a possibility to switch the "add post form" for an "add question form" and that the news question show in the "space activity panel" and a post with the question is automatically created !!! I think that will be even better.^^)

PS: As the Q/A is an important module for my project, I work "a lot" on it, for the moment only about the "design" to fit with my theme... But I'm thinking about many things for it, like the suggestion i already made, but also a "badge tag" system for the question, such as "Close" and "Urgent" for example... "Close" will mean that the owner "close" the question cause his problem is resolved (people still can answer and comment as normal, it's just "tag" to show in the global view of the "future" category).

Oh and I think that answers should be notified to the creator of the question (that will be nice...^^)

**Comment by benmag** [comment]
Any help we can get improving this module is more than welcomed! 

The category one is a tricky one. I understand your point about people just posting to the Space's wall instead of asking a question. I don't mind the idea of what you suggested. The Spaces was mostly about categorising things anyway

I see [Flarum](https://discuss.flarum.org/) as a really great example of the kinds of functionality this module could eventually have - is this similar to what you had in mind for categories and closing etc?

@hfortune is another active user of this module and may have some thoughts on this too.

**Comment by LokyStaz** [comment]
hahaha yep ^^ I like flarum (they do an amazing works)...
But I think the edit I made will be better no? :
Or a better integration in the space... Like : The number of question in the space header (such as posts, members...), a possibility to switch the "add post form" for an "add question form" and that the news question show in the "space activity panel" and a simple post with the question title is automatically created !!! and I think that answers should be notified to the creator of the question...
