### ISSUE TITLE
Accepted answer, error static method ?

### ISSUE THREAD

**Issue by LokyStaz** [ConnectedCommunities/humhub-modules-questionanswer#39]
Hi.. I get an error when voting on a question for example!!

> Non-static method humhub\modules\questionanswer\models\QuestionVotes::findAcceptedAnswer() should not be called statically

apparently coming from the "QuestionVotes.php" line 226...

> $previousAccepted = QuestionVotes::findAcceptedAnswer($question->id);

Thanks (again ^^)

**Comment by benmag** [comment]
This should be fixed now with my latest commit
