### ISSUE TITLE
about the inline CSS

### ISSUE THREAD

**Issue by WebCrew** [ConnectedCommunities/humhub-modules-questionanswer#41]
Hi mates,

first of all - You`ve done a great HH Module, I like it a lot. 

There is one little issue, for my opinion it is not good and also not very userfriendly to edit, if the CSS is stored inline as part of the "view files". It is also not good in case of SEO. So it would be extremly helpful if You make a extra CSS folder and CSS files.

Kind regards, Andy

**Comment by benmag** [comment]
That's a good point. I've made a start on that. CSS is now in `resources/css/default.css`.
