### ISSUE TITLE
Database Exception – yii\db\Exception

### ISSUE THREAD

**Issue by MarcWoodyard** [ConnectedCommunities/humhub-modules-questionanswer#44]
When I activated the module, this error popped up. Is this normal? 

![error](https://cloud.githubusercontent.com/assets/5026965/21880196/6f10deac-d852-11e6-83f1-72eb8194543b.PNG)

**Comment by Felli** [comment]
Check to make sure all of your PHP extensions are up-to-date.

**Comment by devfelipereis** [comment]
I got the same...

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at' in /var/www/pandohub/protected/vendor/yiisoft/yii2/db/Command.php:846

EDIT:

Adding ALLOW_INVALID_DATES to sql_mode works for me.

**Comment by Felli** [comment]
I tried my best to fix this issue in my P/R hopefully that works for you @devfelipereis & @MarcWoodyard?

**Comment by benmag** [comment]
I believe @Felli 's PR resolves this
