### ISSUE TITLE
Q: Is it possible to remove Tag posts?

### ISSUE THREAD

**Issue by Felli** [ConnectedCommunities/humhub-modules-questionanswer#46]
As the title entails, is it possible to remove a tag post altogether from the wall?

### Example
Remove the post that is made once a tag is added to a question and make it so that this never displays as a post.
![](https://image.prntscr.com/image/GR3iO2anSfSKhznFqoOIhw.png)

**Comment by benmag** [comment]
The quick fix to prevent this is setting 

```
	/**
	 * @inheritdoc
	 */
	public $autoAddToWall = false;

	/**
	 * @inheritdoc
	 */
	public $wallEntryClass = "";// "humhub\modules\questionanswer\widgets\TagWallEntryWidget";


```

in `models/Tag.php`
