### ISSUE TITLE
Add new Question fails

### ISSUE THREAD

**Issue by kluthe** [ConnectedCommunities/humhub-modules-questionanswer#47]
Hey. Congratulations to this module! Especially for the voting. It is a amazing function! I have no luck to get it work. I installed everything in protected/modules directory but when i add question i get an error Page. Can you help me please?

----------
Unknown Property – yii\base\UnknownPropertyException

Getting unknown property: humhub\modules\questionanswer\models\Question::pinned
1. in /var/www/html/protected/vendor/yiisoft/yii2/base/Component.php at line 147
138139140141142143144145146147148149150151152153154155156            if ($behavior->canGetProperty($name)) {
                return $behavior->$name;
            }
        }
 
        if (method_exists($this, 'set' . $name)) {
            throw new InvalidCallException('Getting write-only property: ' . get_class($this) . '::' . $name);
        }
 
        throw new UnknownPropertyException('Getting unknown property: ' . get_class($this) . '::' . $name);
    }
 
    /**
     * Sets the value of a component property.
     * This method will check in the following order and act accordingly:
     *
     *  - a property defined by a setter: set the property value
     *  - an event in the format of "on xyz": attach the handler to the event "xyz"
     *  - a behavior in the format of "as xyz": attach the behavior named as "xyz"
2. in /var/www/html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 285 – yii\base\Component::__get('pinned')
3. in /var/www/html/protected/humhub/modules/content/components/ContentActiveRecord.php at line 146 – yii\db\BaseActiveRecord::__get('pinned')
140141142143144145146147148149150151152                $content = new Content();
                $this->populateRelation('content', $content);
                $content->setPolymorphicRelation($this);
            }
            return $content;
        }
        return parent::__get($name);
    }
 
    /**
     * Returns the name of this type of content.
     * You need to override this method in your content implementation.
     *
4. in /var/www/html/protected/vendor/yiisoft/yii2/validators/Validator.php at line 263 – humhub\modules\content\components\ContentActiveRecord::__get('pinned')
5. in /var/www/html/protected/vendor/yiisoft/yii2/base/Model.php at line 358 – yii\validators\Validator::validateAttributes(humhub\modules\questionanswer\models\Question, ['pinned', 'created_by', 'updated_by'])
6. in /var/www/html/protected/modules/qa/controllers/QuestionController.php at line 178 – yii\base\Model::validate()
172173174175176177178179180181182183184                $containerClass = User::className();
                $contentContainer = $containerClass::findOne(['guid' => Yii::$app->getUser()->guid]);
                $question->content->container = $contentContainer;
            }
 
 
            if ($question->validate()) {
 
                // Save and Index the `content` object the search engine
                // NOTE: You could probably do this by adding in container->visibility yourself
                // NOTE2: it's also worth looking at doing this the right way and making Q&A a module
                //			which can be enabled on Spaces and Users.
                // 		This will free us from needing to do work arounds like below :)
7. humhub\modules\questionanswer\controllers\QuestionController::actionCreate()
8. in /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array([humhub\modules\questionanswer\controllers\QuestionController, 'actionCreate'], [])
9. in /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php at line 156 – yii\base\InlineAction::runWithParams(['r' => 'questionanswer/question/create', '_pjax' => '#layout-content', '_' => '1505641149366'])
10. in /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php at line 523 – yii\base\Controller::runAction('create', ['r' => 'questionanswer/question/create', '_pjax' => '#layout-content', '_' => '1505641149366'])
11. in /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php at line 102 – yii\base\Module::runAction('questionanswer/question/create', ['r' => 'questionanswer/question/create', '_pjax' => '#layout-content', '_' => '1505641149366'])
12. in /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php at line 380 – yii\web\Application::handleRequest(humhub\components\Request)
13. in /var/www/html/index.php at line 25 – yii\base\Application::run()
19202122232425    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
(new humhub\components\Application($config))->run();

--------

**Comment by benmag** [comment]
This is likely because some migrations have not taken affect on your installation. 

In your `question` table there should be an integer based `pinned` with a default of `0`.

Please check to see that your tables match what's set out in the migrations file: https://github.com/ConnectedCommunities/humhub-modules-questionanswer/tree/master/migrations

If they don't, update your tables to match and it should work
