### ISSUE TITLE
How to remove Unused Tags ?

### ISSUE THREAD

**Issue by swapnil2sutar** [ConnectedCommunities/humhub-modules-questionanswer#48]
I have added a question with Post title, Post Text & Tag field. Here I can delete that post but not the tag. created tags remain in database & there is no option to delete or update that tag. From where I can remove or delete that tag. If it is not possible from UI, Please give me mysql query to do this. 
Thanks in Advance :-)

**Comment by benmag** [comment]
There's no admin functionality for that yet (although, I'd happily accept any PRs to introduce it!) 

For the time being you'll have to delete the row from the `tag` table. Just make sure there's no matching `tag_id` in the `question_tag` table before deleting 

Example Query: 
```
DELETE FROM `tag` WHERE `tag` = 'foobar';
```
