### ISSUE TITLE
Follow a question with notification or email

### ISSUE THREAD

**Issue by tecmint** [ConnectedCommunities/humhub-modules-questionanswer#49]
Hi, it would be useful to be able to follow a tag or a space / global Q&A with notifications. Ideally both an email and humhub notification of new questions or answers

Currently users are missing questions if they don't check the module daily. Is there anyway to integrate email notifications into Q&A module?

Thanks for the useful module

**Comment by benmag** [comment]
Great suggestion. 

This isn't currently implemented but I expect one day in the future, we could hook this module up to the HumHub notification system

Closing this for now but will be on the todo list
