### ISSUE TITLE
Questions are not appearing on Other users wall (Dashboard)

### ISSUE THREAD

**Issue by swapnil2sutar** [ConnectedCommunities/humhub-modules-questionanswer#52]
I have selected **Global** mode in Q&A module.  Also in `questionanswer/models/Question.php` `$autoAddToWall` changed to `true`. But still Questions posted by user are not visible on other users wall (Dashboard). User can only see Questions which they posted, they can't see others questions & related feed on their wall. I want questions & feeds on other users as well so they can answer.

Also, How we can get Tag drop-down instead of input field while posting questions. Please help

**Comment by Felli** [comment]
1. Content posted by default can only be viewed on the dashboard by followers or friends, I believe this is more of an issue with HumHub than the module itself, changing `$autoAddToWall` won't fix this.
2. I believe using select2 (Which is used for HumHub dropdown fields) for this and query the tags could possibly work.
