### ISSUE TITLE
An unexpected server error occurred. While updating or deleting Questions Answers & Tags

### ISSUE THREAD

**Issue by swapnil2sutar** [ConnectedCommunities/humhub-modules-questionanswer#53]
Hello @benmag @Felli @liamcripwell @knich17 @byronmejia 

Whenever I update or delete Questions, Answers Tags I get errors. 

`{
    "url": "/decode/index.php?r=dashboard%2Fdashboard%2Fstream&mode=activity",
    "status": 500,
    "response": {
        "name": "Exception",
        "message": "Calling unknown method: humhub\\modules\\questionanswer\\models\\Tag::createUrl()",
        "code": 0,
        "type": "yii\\base\\UnknownMethodException",
        "file": "/var/www/html/decode/protected/vendor/yiisoft/yii2/base/Component.php",
        "line": 290,
        "stack-trace": [
            "#0 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): yii\\base\\Component->__call('createUrl', Array)",
            "#1 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): humhub\\modules\\questionanswer\\models\\Tag->createUrl('//questionanswe...', Array)",
            "#2 /var/www/html/decode/protected/humhub/modules/content/models/Content.php(401): humhub\\modules\\questionanswer\\models\\Tag->getUrl()",
            "#3 /var/www/html/decode/protected/humhub/components/SocialActivity.php(230): humhub\\modules\\content\\models\\Content->getUrl()",
            "#4 /var/www/html/decode/protected/humhub/components/SocialActivity.php(148): humhub\\components\\SocialActivity->getUrl()",
            "#5 /var/www/html/decode/protected/humhub/modules/activity/components/BaseActivity.php(59): humhub\\components\\SocialActivity->getViewParams(Array)",
            "#6 /var/www/html/decode/protected/humhub/components/rendering/LayoutRenderer.php(49): humhub\\modules\\activity\\components\\BaseActivity->getViewParams(Array)",
            "#7 /var/www/html/decode/protected/humhub/modules/activity/components/ActivityWebRenderer.php(51): humhub\\components\\rendering\\LayoutRenderer->render(Object(humhub\\modules\\content\\activities\\ContentCreated), Array)",
            "#8 /var/www/html/decode/protected/humhub/modules/activity/models/Activity.php(114): humhub\\modules\\activity\\components\\ActivityWebRenderer->render(Object(humhub\\modules\\content\\activities\\ContentCreated))",
            "#9 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(324): humhub\\modules\\activity\\models\\Activity->getWallOut(Array)",
            "#10 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(358): humhub\\modules\\stream\\actions\\Stream::renderEntry(Object(humhub\\modules\\activity\\models\\Activity), false)",
            "#11 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(233): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
            "#12 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
            "#13 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
            "#14 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams(Array)",
            "#15 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
            "#16 /var/www/html/decode/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('dashboard/dashb...', Array)",
            "#17 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
            "#18 /var/www/html/decode/index.php(25): yii\\base\\Application->run()",
            "#19 {main}"
        ]
    },
    "textStatus": "error",
    "dataType": "json",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"name\":\"Exception\",\"message\":\"Calling unknown method: humhub\\\\modules\\\\questionanswer\\\\models\\\\Tag::createUrl()\",\"code\":0,\"type\":\"yii\\\\base\\\\UnknownMethodException\",\"file\":\"/var/www/html/decode/protected/vendor/yiisoft/yii2/base/Component.php\",\"line\":290,\"stack-trace\":[\"#0 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): yii\\\\base\\\\Component->__call('createUrl', Array)\",\"#1 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): humhub\\\\modules\\\\questionanswer\\\\models\\\\Tag->createUrl('//questionanswe...', Array)\",\"#2 /var/www/html/decode/protected/humhub/modules/content/models/Content.php(401): humhub\\\\modules\\\\questionanswer\\\\models\\\\Tag->getUrl()\",\"#3 /var/www/html/decode/protected/humhub/components/SocialActivity.php(230): humhub\\\\modules\\\\content\\\\models\\\\Content->getUrl()\",\"#4 /var/www/html/decode/protected/humhub/components/SocialActivity.php(148): humhub\\\\components\\\\SocialActivity->getUrl()\",\"#5 /var/www/html/decode/protected/humhub/modules/activity/components/BaseActivity.php(59): humhub\\\\components\\\\SocialActivity->getViewParams(Array)\",\"#6 /var/www/html/decode/protected/humhub/components/rendering/LayoutRenderer.php(49): humhub\\\\modules\\\\activity\\\\components\\\\BaseActivity->getViewParams(Array)\",\"#7 /var/www/html/decode/protected/humhub/modules/activity/components/ActivityWebRenderer.php(51): humhub\\\\components\\\\rendering\\\\LayoutRenderer->render(Object(humhub\\\\modules\\\\content\\\\activities\\\\ContentCreated), Array)\",\"#8 /var/www/html/decode/protected/humhub/modules/activity/models/Activity.php(114): humhub\\\\modules\\\\activity\\\\components\\\\ActivityWebRenderer->render(Object(humhub\\\\modules\\\\content\\\\activities\\\\ContentCreated))\",\"#9 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(324): humhub\\\\modules\\\\activity\\\\models\\\\Activity->getWallOut(Array)\",\"#10 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(358): humhub\\\\modules\\\\stream\\\\actions\\\\Stream::renderEntry(Object(humhub\\\\modules\\\\activity\\\\models\\\\Activity), false)\",\"#11 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(233): humhub\\\\modules\\\\stream\\\\actions\\\\Stream::getContentResultEntry(Object(humhub\\\\modules\\\\content\\\\models\\\\Content))\",\"#12 [internal function]: humhub\\\\modules\\\\stream\\\\actions\\\\Stream->run()\",\"#13 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)\",\"#14 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\\\base\\\\Action->runWithParams(Array)\",\"#15 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\\\base\\\\Controller->runAction('stream', Array)\",\"#16 /var/www/html/decode/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\\\base\\\\Module->runAction('dashboard/dashb...', Array)\",\"#17 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\\\web\\\\Application->handleRequest(Object(humhub\\\\components\\\\Request))\",\"#18 /var/www/html/decode/index.php(25): yii\\\\base\\\\Application->run()\",\"#19 {main}\"]}",
        "responseJSON": {
            "name": "Exception",
            "message": "Calling unknown method: humhub\\modules\\questionanswer\\models\\Tag::createUrl()",
            "code": 0,
            "type": "yii\\base\\UnknownMethodException",
            "file": "/var/www/html/decode/protected/vendor/yiisoft/yii2/base/Component.php",
            "line": 290,
            "stack-trace": [
                "#0 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): yii\\base\\Component->__call('createUrl', Array)",
                "#1 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): humhub\\modules\\questionanswer\\models\\Tag->createUrl('//questionanswe...', Array)",
                "#2 /var/www/html/decode/protected/humhub/modules/content/models/Content.php(401): humhub\\modules\\questionanswer\\models\\Tag->getUrl()",
                "#3 /var/www/html/decode/protected/humhub/components/SocialActivity.php(230): humhub\\modules\\content\\models\\Content->getUrl()",
                "#4 /var/www/html/decode/protected/humhub/components/SocialActivity.php(148): humhub\\components\\SocialActivity->getUrl()",
                "#5 /var/www/html/decode/protected/humhub/modules/activity/components/BaseActivity.php(59): humhub\\components\\SocialActivity->getViewParams(Array)",
                "#6 /var/www/html/decode/protected/humhub/components/rendering/LayoutRenderer.php(49): humhub\\modules\\activity\\components\\BaseActivity->getViewParams(Array)",
                "#7 /var/www/html/decode/protected/humhub/modules/activity/components/ActivityWebRenderer.php(51): humhub\\components\\rendering\\LayoutRenderer->render(Object(humhub\\modules\\content\\activities\\ContentCreated), Array)",
                "#8 /var/www/html/decode/protected/humhub/modules/activity/models/Activity.php(114): humhub\\modules\\activity\\components\\ActivityWebRenderer->render(Object(humhub\\modules\\content\\activities\\ContentCreated))",
                "#9 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(324): humhub\\modules\\activity\\models\\Activity->getWallOut(Array)",
                "#10 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(358): humhub\\modules\\stream\\actions\\Stream::renderEntry(Object(humhub\\modules\\activity\\models\\Activity), false)",
                "#11 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(233): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
                "#12 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
                "#13 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
                "#14 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams(Array)",
                "#15 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
                "#16 /var/www/html/decode/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('dashboard/dashb...', Array)",
                "#17 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
                "#18 /var/www/html/decode/index.php(25): yii\\base\\Application->run()",
                "#19 {main}"
            ]
        },
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "name": "Exception",
    "message": "Calling unknown method: humhub\\modules\\questionanswer\\models\\Tag::createUrl()",
    "code": 0,
    "type": "yii\\base\\UnknownMethodException",
    "file": "/var/www/html/decode/protected/vendor/yiisoft/yii2/base/Component.php",
    "line": 290,
    "stack-trace": [
        "#0 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): yii\\base\\Component->__call('createUrl', Array)",
        "#1 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): humhub\\modules\\questionanswer\\models\\Tag->createUrl('//questionanswe...', Array)",
        "#2 /var/www/html/decode/protected/humhub/modules/content/models/Content.php(401): humhub\\modules\\questionanswer\\models\\Tag->getUrl()",
        "#3 /var/www/html/decode/protected/humhub/components/SocialActivity.php(230): humhub\\modules\\content\\models\\Content->getUrl()",
        "#4 /var/www/html/decode/protected/humhub/components/SocialActivity.php(148): humhub\\components\\SocialActivity->getUrl()",
        "#5 /var/www/html/decode/protected/humhub/modules/activity/components/BaseActivity.php(59): humhub\\components\\SocialActivity->getViewParams(Array)",
        "#6 /var/www/html/decode/protected/humhub/components/rendering/LayoutRenderer.php(49): humhub\\modules\\activity\\components\\BaseActivity->getViewParams(Array)",
        "#7 /var/www/html/decode/protected/humhub/modules/activity/components/ActivityWebRenderer.php(51): humhub\\components\\rendering\\LayoutRenderer->render(Object(humhub\\modules\\content\\activities\\ContentCreated), Array)",
        "#8 /var/www/html/decode/protected/humhub/modules/activity/models/Activity.php(114): humhub\\modules\\activity\\components\\ActivityWebRenderer->render(Object(humhub\\modules\\content\\activities\\ContentCreated))",
        "#9 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(324): humhub\\modules\\activity\\models\\Activity->getWallOut(Array)",
        "#10 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(358): humhub\\modules\\stream\\actions\\Stream::renderEntry(Object(humhub\\modules\\activity\\models\\Activity), false)",
        "#11 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(233): humhub\\modules\\stream\\actions\\Stream::getContentResultEntry(Object(humhub\\modules\\content\\models\\Content))",
        "#12 [internal function]: humhub\\modules\\stream\\actions\\Stream->run()",
        "#13 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
        "#14 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams(Array)",
        "#15 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('stream', Array)",
        "#16 /var/www/html/decode/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('dashboard/dashb...', Array)",
        "#17 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
        "#18 /var/www/html/decode/index.php(25): yii\\base\\Application->run()",
        "#19 {main}"
    ],
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}`

**From Error Log:** 
`$_GET = [ 'r' => 'dashboard/dashboard/stream' 'mode' => 'activity' 'StreamQuery' => [ 'sort' => 'c' 'from' => '0' 'limit' => '10' 'suppressionsOnly' => 'false' ] ] $_SERVER = [ 'HTTP_HOST' => 'localhost' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_X_CSRF_TOKEN' => 'BEocK46P0-clvc7rA06pEbs-lP1K2IxjnXwFNc6Cpx8IakxLl93_ajVRjA-O9AGgzNyROcoLlNIKE58GvdRfDA==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36' 'HTTP_REFERER' => 'http://localhost/decode/index.php?r=dashboard%2Fdashboard' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8' 'HTTP_COOKIE' => 'pm_getting-started-panel=expanded; pm_groups-statistics-panel=expanded; pm_space-members-panel=expanded; optimizelyEndUserId=oeu1503999895509r0.30226084804473974; _drip_client_6994213=vid%253Dd257b940462f0135de090e3a7ac416fc%2526pageViews%253D19%2526sessionPageCount%253D1%2526lastVisitedAt%253D1505029089043%2526weeklySessionCount%253D9%2526lastSessionAt%253D1505029089043; __smListBuilderShown=Mon%20Sep%2018%202017%2012:57:49%20GMT+0530%20(IST); optimizelySegments=%7B%223816780720%22%3A%22false%22%2C%223818041290%22%3A%22gc%22%2C%223826150633%22%3A%22direct%22%7D; optimizelyBuckets=%7B%7D; __smToken=Il50mL4GF411ScsYwdChnNxF; __smUser=162881e9-bf35-4216-a2dc-5407ab923685; intercom-id-h5gk3vmz=fbda6b14-d433-4286-afe5-e8ea15f39829; _ga=GA1.1.736111195.1499420154; PHPSESSID=g5ch5sjvbrah5ck7vame8lq3c1; _csrf=d63eff33b882308f574d46480f06775b2bcd10c3a863e573d68ae769c5893a06a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22%0C+P%60%19R%2C%8D%10%ECB%E4%8D%BA%A8%B1w%E2%05%C4%80%D3%18%B1%97o%9A3sV%F8%13%22%3B%7D; _identity=89d1c9871f49a2f05fc5d5287d47fa84a4ad702ac94df3de12370bd778e3e7cca%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%2270df59b4-adb8-46c8-839f-ca271c8bbda2%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at localhost Port 80</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)' 'SERVER_NAME' => 'localhost' 'SERVER_ADDR' => '::1' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '::1' 'DOCUMENT_ROOT' => '/var/www/html' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/html' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/var/www/html/decode/index.php' 'REMOTE_PORT' => '42940' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=dashboard%2Fdashboard%2Fstream&mode=activity&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=10&StreamQuery%5BsuppressionsOnly%5D=false' 'REQUEST_URI' => '/decode/index.php?r=dashboard%2Fdashboard%2Fstream&mode=activity&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=10&StreamQuery%5BsuppressionsOnly%5D=false' 'SCRIPT_NAME' => '/decode/index.php' 'PHP_SELF' => '/decode/index.php' 'REQUEST_TIME_FLOAT' => 1510047009.671 'REQUEST_TIME' => 1510047009 ]
`

`exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: humhub\modules\questionanswer\models\Tag::createUrl()' in /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Component.php:290 Stack trace: #0 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): yii\base\Component->__call('createUrl', Array) #1 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): humhub\modules\questionanswer\models\Tag->createUrl('//questionanswe...', Array) #2 /var/www/html/decode/protected/humhub/modules/content/models/Content.php(401): humhub\modules\questionanswer\models\Tag->getUrl() #3 /var/www/html/decode/protected/humhub/components/SocialActivity.php(230): humhub\modules\content\models\Content->getUrl() #4 /var/www/html/decode/protected/humhub/components/SocialActivity.php(148): humhub\components\SocialActivity->getUrl() #5 /var/www/html/decode/protected/humhub/modules/activity/components/BaseActivity.php(59): humhub\components\SocialActivity->getViewParams(Array) #6 /var/www/html/decode/protected/humhub/components/rendering/LayoutRenderer.php(49): humhub\modules\activity\components\BaseActivity->getViewParams(Array) #7 /var/www/html/decode/protected/humhub/modules/activity/components/ActivityWebRenderer.php(51): humhub\components\rendering\LayoutRenderer->render(Object(humhub\modules\content\activities\ContentCreated), Array) #8 /var/www/html/decode/protected/humhub/modules/activity/models/Activity.php(114): humhub\modules\activity\components\ActivityWebRenderer->render(Object(humhub\modules\content\activities\ContentCreated)) #9 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(324): humhub\modules\activity\models\Activity->getWallOut(Array) #10 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(358): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\activity\models\Activity), false) #11 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(233): humhub\modules\stream\actions\Stream::getContentResultEntry(Object(humhub\modules\content\models\Content)) #12 [internal function]: humhub\modules\stream\actions\Stream->run() #13 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #14 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array) #15 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('stream', Array) #16 /var/www/html/decode/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('dashboard/dashb...', Array) #17 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #18 /var/www/html/decode/index.php(25): yii\base\Application->run() #19 {main}
`
`exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: humhub\modules\questionanswer\models\Tag::createUrl()' in /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Component.php:290 Stack trace: #0 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): yii\base\Component->__call('createUrl', Array) #1 /var/www/html/decode/protected/modules/questionanswer/models/Tag.php(157): humhub\modules\questionanswer\models\Tag->createUrl('//questionanswe...', Array) #2 /var/www/html/decode/protected/humhub/modules/content/models/Content.php(401): humhub\modules\questionanswer\models\Tag->getUrl() #3 /var/www/html/decode/protected/humhub/components/SocialActivity.php(230): humhub\modules\content\models\Content->getUrl() #4 /var/www/html/decode/protected/humhub/components/SocialActivity.php(148): humhub\components\SocialActivity->getUrl() #5 /var/www/html/decode/protected/humhub/modules/activity/components/BaseActivity.php(59): humhub\components\SocialActivity->getViewParams(Array) #6 /var/www/html/decode/protected/humhub/components/rendering/LayoutRenderer.php(49): humhub\modules\activity\components\BaseActivity->getViewParams(Array) #7 /var/www/html/decode/protected/humhub/modules/activity/components/ActivityWebRenderer.php(51): humhub\components\rendering\LayoutRenderer->render(Object(humhub\modules\content\activities\ContentCreated), Array) #8 /var/www/html/decode/protected/humhub/modules/activity/models/Activity.php(114): humhub\modules\activity\components\ActivityWebRenderer->render(Object(humhub\modules\content\activities\ContentCreated)) #9 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(324): humhub\modules\activity\models\Activity->getWallOut(Array) #10 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(358): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\activity\models\Activity), false) #11 /var/www/html/decode/protected/humhub/modules/stream/actions/Stream.php(233): humhub\modules\stream\actions\Stream::getContentResultEntry(Object(humhub\modules\content\models\Content)) #12 [internal function]: humhub\modules\stream\actions\Stream->run() #13 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #14 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array) #15 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('stream', Array) #16 /var/www/html/decode/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('dashboard/dashb...', Array) #17 /var/www/html/decode/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #18 /var/www/html/decode/index.php(25): yii\base\Application->run() #19 {main}
`

![dashboard](https://user-images.githubusercontent.com/16332853/32486399-879d5e4e-c3cc-11e7-9e40-d5b8081771ea.png)

**Comment by benmag** [comment]
Should be fixed now
