### ISSUE TITLE
How to add translations?

### ISSUE THREAD

**Issue by Attmin** [ConnectedCommunities/humhub-modules-questionanswer#54]
What ist the best way to add translations to this great module?

**Comment by benmag** [comment]
Haven't had a chance to implement things in a way that would allow this to be done right now

HumHub docs cover how to do it: 
http://docs.humhub.org/dev-modules-i18n.html

We'd need to replace all the text that needs to be translated with 
```
Yii::t('QuestionAnswerModule.base', 'English version of text to be translated');
```

Once that's done we could run the `yii message/extract` command to generate the languages files
```
php yii message/extract-module example
```

A pull request on this would be very appreciated

**Comment by blu-IT** [comment]
I would like to contribute to translations (german + italian). Any news?

**Comment by blu-IT** [comment]
> 
> 
> Haven't had a chance to implement things in a way that would allow this to be done right now
> 
> HumHub docs cover how to do it:
> http://docs.humhub.org/dev-modules-i18n.html
> 
> We'd need to replace all the text that needs to be translated with
> 
> ```
> Yii::t('QuestionAnswerModule.base', 'English version of text to be translated');
> ```
> 
> Once that's done we could run the `yii message/extract` command to generate the languages files
> 
> ```
> php yii message/extract-module example
> ```
> 
> A pull request on this would be very appreciated

I would invest some time and start, but I can't find a starting point, as I can't find:
>  QuestionAnswerModule.base

**Update:**
OK, this directory seem so be a good starting point ;-)

https://github.com/ConnectedCommunities/humhub-modules-questionanswer/tree/master/controllers
